### ISSUE TITLE
Add support for Functional.Union

### ISSUE THREAD

**Issue by RyanMarcotte** [RyanMarcotte/Functional.Utilities#6]
The `Functional` suite of libraries provides a `Functional.Unions` package that defines discriminated union types.  Create a new `Functional.Unions.FluentAssertions` NuGet package.

**Comment by Justin-Cooney** [comment]
I was curious as to how we should handle this seeing as this would be an entirely separate NuGet package. Is it acceptable that we have `Functional.Primitives.FluentAssertions` and `Functional.Unions.FluentAssertions` co-exist in this repo?

**Comment by RyanMarcotte** [comment]
In this case, it is fine for the one solution to produce two NuGet packages, yes.  It is the approach I took with the [`Functional.CQS` repository](https://github.com/RyanMarcotte/Functional.CQS).  Having a single solution produce two packages with different versions and release dates becomes awkward when using automated release pipelines, but I am not worried about that.  I have not automated the publishing of packages because updates do not happen often enough to make the automation worth the time investment (to me).

**Comment by Justin-Cooney** [comment]
That sounds good, thanks Ryan. I've added a PR with a draft of this feature for review.
