### ISSUE TITLE
Support for Task<Option<T>> and Task<Result<TSuccess, TFailure>>?

### ISSUE THREAD

**Issue by RyanMarcotte** [RyanMarcotte/Functional.Utilities#7]
It has been proposed to include extension methods for `Task<Option<T>>` and `Task<Result<TSuccess, TFailure>>`.  I am open to the idea, but would like to discuss approaches first.

I had been wondering about the exclusion of `Task<T>` assertions in the `FluentAssertions` library, and - as far as I can tell - they are not included because the maintenance burden would be high: all synchronous methods would have a duplicate asynchronous equivalent.  See https://github.com/fluentassertions/fluentassertions/issues/1305#issuecomment-614617532 for more information.

To date, I have been using the following syntax:

``` csharp
(await option).Should().HaveValue().AndValue.Should().Be(...);
(await result).Should().BeSuccessful().AndSuccessValue.Should().Be(...);
```

I'd like to gather other thoughts before any code is written.  The fact that `FluentAssertions` does not have an extensive set of `Task<T>`-related assertions means there are compromises to be made here, as the following syntax is not possible:

``` csharp
await Option.Some(1337)
    .Should()
    .HaveValue()
    .AndValue() // fine up to this point
    .Should() // FluentAssertions does not define a BeGreaterThan extension method for Task<int>
    .BeGreaterThan(...);
```

**Comment by RyanMarcotte** [comment]
Regarding maintenance burden, the `Functional.Primitives.FluentAssertions` library does not define many extension methods on its own, so having a suite of `Task<T>`-based assertions methods `Should().Be("fine")`.  If we go ahead with this, I am OK with deleting the `Obsolete` methods from the library and releasing a v3 package.  Thoughts on that?

**Comment by Justin-Cooney** [comment]
I was a little unsure of this as well. I can definitely understand why `Fluent Assertions` itself doesn't attempt to maintain a whole suite of `Task<T>` assertions. 

I agree that the use of (await result) or (await option) is suitable for most scenarios. It's only recently that I've been adopting a more Fluent approach to writing unit tests and this is where the Task extensions have lead to some (subjectively) cleaner code.

For example, instead of writing:
```C#
public async Task SomeTest() =>
    await (
    Arrange(Dependency.Succeeds)
    .Arrange(OtherDependency.Succeeds)
    .Act())
    .Should()
    .BeSuccessful()
    .AndSuccessValue.Should().Be("SomeValue"))
```

The extensions allow this:
```C#
public Task SomeTest() =>
    Arrange(Dependency.Succeeds)
    .Arrange(OtherDependency.Succeeds)
    .Act()
    .Should()
    .BeSuccessful()
    .And(value => value.Should().Be("SomeValue"))
```

I can understand if this need is too niche to justify adding the extensions to this library and it's no problem for me to move them to some other internal unit testing package if you feel this isn't the right place for them.

Any thoughts on whether this change feels appropriate here?

**Comment by RyanMarcotte** [comment]
That is an interesting way to write tests.  🙂 

What do the `Arrange(...)`, `Act()`, and surrounding class methods typically look like?  Could you provide a concrete example instead of just pseudo-code so I am not assuming any details?

**Comment by Justin-Cooney** [comment]
Certainly, here's an example of what our BaseFixture and a couple tests might look like:

```C#
public class FluentBaseFixture
{
	protected GitClient Sut;
	protected Mock<GitHttpClient> GitClient;

	public FluentBaseFixture()
	{
		GitClient = new Mock<GitHttpClient>(new Uri("https://test.com/test"), new VssCredentials());
		Sut = new GitClient(GitClient.Object);
	}

	public enum GetItemsAsyncResult { Succeeds, Fails }
	public FluentBaseFixture Arrange(GetItemsAsyncResult result)
	{
		var setup = GitClient.Setup(x => x.GetItemsAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<VersionControlRecursionType>(), null, null, null, null, null, null, It.IsAny<CancellationToken>()));
		if (result == GetItemsAsyncResult.Succeeds)
			setup.ReturnsAsync(new List<GitItem>());
		if (result == GetItemsAsyncResult.Fails)
			setup.Throws(new Exception("GetItemsAsyncFailed"));
		return this;
	}

	public Task<Result<IEnumerable<GitItem>, Exception>> GetAllItemsInRepository()
		=> Sut.GetAllItemsInRepository(CancellationToken.None);
}

public class GetAllItemsInRepository : FluentBaseFixture
{
	[Fact]
	public Task SucceedsWhenGitClientSucceeds() =>
		Arrange(GetItemsAsyncResult.Succeeds)
		.GetAllItemsInRepository()
		.Should()
		.BeSuccessful();

	[Fact]
	public Task WhenGitClientFailsReturnsException() =>
		Arrange(GetItemsAsyncResult.Fails)
		.GetAllItemsInRepository()
		.Should()
		.BeFaulted()
		.And(failure => failure.Message.Should().Be("GetItemsAsyncFailed"));
}
```

**Comment by RyanMarcotte** [comment]
Looks good!  I do like the simplicity of those fluent tests.  It's like the [test data builder pattern](https://blog.ploeh.dk/2017/08/15/test-data-builders-in-c/) applied to the tests themselves.

Thoughts on the following syntax?  It would mirror the naming used for synchronous assertions.

``` csharp
Arrange(GetItemsAsyncResult.Fails)
		.GetAllItemsInRepository()
		.Should()
		.BeFaulted()
		.AndFailureValue(e => e.Message.Should().Be("GetItemsAsyncFailed"));
```

... or `.AndCompletedTaskFailureValue(e => ...)`?  I'm open to other variations of `FailureValue` names.

**Comment by Justin-Cooney** [comment]
You're absolutely right that the test data builder pattern was an inspiration for this. I had used it recently and liked it enough to try applying to the tests themselves.

I agree with your suggestion for a change in syntax. I'm initially leaning towards the idea of using `.AndFailureValue(e => ...)` as this lines up nicely with your original methods.

Thanks for the feedback! I'll start assembling a feature branch for this and spin up a PR for review and discussion.
